[error] GenServer #PID<0.6990.0> terminating
** (FunctionClauseError) no function clause matching in IKnoWeb.SubjectLive.Edit.handle_event/3
    (i_kno 0.1.0) lib/i_kno_web/live/subject_live/edit.ex:15: IKnoWeb.SubjectLive.Edit.handle_event("save", %{"description" => "        Calculus has two major branches, **differential calculus** and **integral calculus**; the former concerns instantaneous rates of change, and the slopes of curves, while the latter concerns accumulation of quantities, and areas under or between curves. These two branches are related to each other by the **fundamental theorem of calculus**, and they make use of the fundamental notions of convergence of infinite sequences and infinite series to a well-defined limit.\n\n**Infinitesimal calculus** was developed independently in the late 17th century by Isaac Newton and Gottfried Wilhelm Leibniz.Later work, including codifying the idea of limits, put these developments on a more solid conceptual footing. Today, calculus has widespread uses in science, engineering, and social science.\n      ", "name" => "Calculus", "summary" => "Calculus is the mathematical study of continuous change."}, #Phoenix.LiveView.Socket<id: "phx-F1WINs6kjOXRIkrF", endpoint: IKnoWeb.Endpoint, view: IKnoWeb.SubjectLive.Edit, parent_pid: nil, root_pid: #PID<0.6990.0>, router: IKnoWeb.Router, assigns: %{__changed__: %{}, flash: %{}, live_action: nil, subject: %IKno.Knowledge.Subject{__meta__: #Ecto.Schema.Metadata<:loaded, "subjects">, id: 2, description: "Calculus has two major branches, **differential calculus** and **integral calculus**; the former concerns instantaneous rates of change, and the slopes of curves, while the latter concerns accumulation of quantities, and areas under or between curves. These two branches are related to each other by the **fundamental theorem of calculus**, and they make use of the fundamental notions of convergence of infinite sequences and infinite series to a well-defined limit.\n\n**Infinitesimal calculus** was developed independently in the late 17th century by Isaac Newton and Gottfried Wilhelm Leibniz.Later work, including codifying the idea of limits, put these developments on a more solid conceptual footing. Today, calculus has widespread uses in science, engineering, and social science.", name: "Calculus", summary: "Calculus is the mathematical study of continuous change.", topics: #Ecto.Association.NotLoaded<association :topics is not loaded>, inserted_at: ~N[2023-04-07 02:35:01], updated_at: ~N[2023-04-07 19:23:48]}}, transport_pid: #PID<0.6942.0>, ...>)
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:401: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /Users/charlesirvine/src/i_kno/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:221: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.2) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F1WINs6kjOXRIkrF", event: "event", payload: %{"event" => "save", "type" => "form", "value" => "name=Calculus&summary=Calculus+is+the+mathematical+study+of+continuous+change.&description=++++++++Calculus+has+two+major+branches%2C+**differential+calculus**+and+**integral+calculus**%3B+the+former+concerns+instantaneous+rates+of+change%2C+and+the+slopes+of+curves%2C+while+the+latter+concerns+accumulation+of+quantities%2C+and+areas+under+or+between+curves.+These+two+branches+are+related+to+each+other+by+the+**fundamental+theorem+of+calculus**%2C+and+they+make+use+of+the+fundamental+notions+of+convergence+of+infinite+sequences+and+infinite+series+to+a+well-defined+limit.%0A%0A**Infinitesimal+calculus**+was+developed+independently+in+the+late+17th+century+by+Isaac+Newton+and+Gottfried+Wilhelm+Leibniz.Later+work%2C+including+codifying+the+idea+of+limits%2C+put+these+developments+on+a+more+solid+conceptual+footing.+Today%2C+calculus+has+widespread+uses+in+science%2C+engineering%2C+and+social+science.%0A++++++"}, ref: "48", join_ref: "46"}

